# Generated by Django 4.0.4 on 2022-04-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_posts_post_rename_tags_tag_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag'),
        ),
    ]
